# Generated by Django 3.1.3 on 2020-12-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prejub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='s_text',
            new_name='suggestion',
        ),
    ]
